### ISSUE TITLE
Eclipse plugin: math formulas not shown after update to 1.1.25

### ISSUE THREAD

**Issue by danieleb2000** [hallvard/plantuml#131]
Screenshot:

![image](https://user-images.githubusercontent.com/38882361/115695386-0e7b0d80-a362-11eb-8587-a61d5724ed4d.png)

**Comment by danieleb2000** [comment]
Screenshot 1.1.25:

![image](https://user-images.githubusercontent.com/38882361/115695849-6ade2d00-a362-11eb-8e93-0784f90a240b.png)

**Comment by hallvard** [comment]
Perhaps there's some dependency issue that prevents the jlatexmath plugin to be activated/used with 1.1.25.

**Comment by danieleb2000** [comment]
Everything has been installed from scratch. Some hints about how to investigate the dependency issue?

**Comment by hallvard** [comment]
Strange... when launched from my dev. eclipse the PlantUML view shows it as expected, while the PlantUML Svg view throws an exception:

formula=R(t) = e^(-lambda*t)
Latex={R}{\left({t}\right)}={e}^{{-\lambda\cdot{t}}}
java.lang.ClassNotFoundException: org.apache.batik.dom.GenericDOMImplementation cannot be found by net.sourceforge.plantuml.lib_1.2021.3
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:516)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:171)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at net.sourceforge.plantuml.math.ConverterSvg.getSvg(ConverterSvg.java:84)
	at net.sourceforge.plantuml.math.LatexBuilder.getSvg(LatexBuilder.java:74)
	at net.sourceforge.plantuml.math.AsciiMath.getSvg(AsciiMath.java:99)

**Comment by danieleb2000** [comment]
By me also with normal diagram it is not correctly shown. Maybe some needed dependency is not installed?

**Comment by danieleb2000** [comment]
Error still present in 1.1.26. 
Root cause understood?

**Comment by hallvard** [comment]
I agree, I don't seem to have understood the underlying problem... Which Eclipse version do you run on?

**Comment by danieleb2000** [comment]
Issue persistent on both the following Eclipse versions:

Eclipse IDE for C/C++ Developers 2019-06 (4.12.0)
Eclipse IDE for C/C++ Developers (includes Incubating components) Version: 2021-03 (4.19.0)

**Comment by hallvard** [comment]
I need stack traces to be able to debug this, do you find that in the Error Log view?

**Comment by danieleb2000** [comment]
> I need stack traces to be able to debug this, do you find that in the Error Log view?

What should I search for? I have only 3 entries in the Error Log, none of them is related to Plantuml stuff.

**Comment by danieleb2000** [comment]
> I need stack traces to be able to debug this, do you find that in the Error Log view?

I got the following 3 errors in the Error Log view:  

0) org.eclipse.egit.ui:  Warning: The environment variable HOME is not set. The following directory will be used to store the Git
An exception stack trace is not available.

1) org.eclipse.ui.ide: Not properly disposed SWT resource

java.lang.Error: SWT Resource was not properly disposed
	at org.eclipse.swt.graphics.Resource.initNonDisposeTracking(Resource.java:172)
	at org.eclipse.swt.graphics.Resource.<init>(Resource.java:120)
	at org.eclipse.swt.graphics.Image.<init>(Image.java:165)
	at org.eclipse.swt.graphics.Image.win32_new(Image.java:2163)
	at org.eclipse.swt.widgets.TaskBar.createShellLink(TaskBar.java:168)
	at org.eclipse.swt.widgets.TaskBar.createShellLinkArray(TaskBar.java:208)
	at org.eclipse.swt.widgets.TaskBar.setMenu(TaskBar.java:382)
	at org.eclipse.swt.widgets.TaskItem.setMenu(TaskItem.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.mylyn.commons.workbench.TaskBarManager$TaskBarMenuManager.setMenuOnTaskItem(TaskBarManager.java:121)
	at org.eclipse.mylyn.commons.workbench.TaskBarManager$TaskBarMenuManager.update(TaskBarManager.java:112)
	at org.eclipse.jface.action.MenuManager.update(MenuManager.java:673)
	at org.eclipse.mylyn.internal.tasks.ui.TasksUiPlugin.addSystemTaskBarActions(TasksUiPlugin.java:479)
	at org.eclipse.mylyn.internal.tasks.ui.TasksUiPlugin.access$7(TasksUiPlugin.java:458)
	at org.eclipse.mylyn.internal.tasks.ui.TasksUiPlugin$TasksUiInitializationJob.runInUIThread(TasksUiPlugin.java:394)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:95)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4001)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3629)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)


2) org.eclipse.ui.ide: Not properly disposed SWT resource

java.lang.Error: SWT Resource was not properly disposed
	at org.eclipse.swt.graphics.Resource.initNonDisposeTracking(Resource.java:172)
	at org.eclipse.swt.graphics.Resource.<init>(Resource.java:120)
	at org.eclipse.swt.graphics.Image.<init>(Image.java:165)
	at org.eclipse.swt.graphics.Image.win32_new(Image.java:2163)
	at org.eclipse.swt.widgets.TaskBar.createShellLink(TaskBar.java:168)
	at org.eclipse.swt.widgets.TaskBar.createShellLinkArray(TaskBar.java:208)
	at org.eclipse.swt.widgets.TaskBar.setMenu(TaskBar.java:382)
	at org.eclipse.swt.widgets.TaskItem.setMenu(TaskItem.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.mylyn.commons.workbench.TaskBarManager$TaskBarMenuManager.setMenuOnTaskItem(TaskBarManager.java:121)
	at org.eclipse.mylyn.commons.workbench.TaskBarManager$TaskBarMenuManager.update(TaskBarManager.java:112)
	at org.eclipse.jface.action.MenuManager.update(MenuManager.java:673)
	at org.eclipse.mylyn.internal.tasks.ui.TasksUiPlugin.addSystemTaskBarActions(TasksUiPlugin.java:479)
	at org.eclipse.mylyn.internal.tasks.ui.TasksUiPlugin.access$7(TasksUiPlugin.java:458)
	at org.eclipse.mylyn.internal.tasks.ui.TasksUiPlugin$TasksUiInitializationJob.runInUIThread(TasksUiPlugin.java:394)
	at org.eclipse.ui.progress.UIJob.lambda$0(UIJob.java:95)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4001)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3629)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1157)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:644)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:551)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:156)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:653)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:590)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1461)

**Comment by danieleb2000** [comment]
Some news about this issue?
