### ISSUE TITLE
NullPointerException when PlantUML project class diaglam view is open and I clicked on the project folder in eclipse

### ISSUE THREAD

**Issue by yujiaao** [hallvard/plantuml#47]
The following will be send to: Eclipse

REPORT

anonymousId         516a52e9-0249-43ca-a39c-d35217076dfb
name                
email               
comment             
eclipseBuildId      4.6.3.M20170301-0400
eclipseProduct      org.eclipse.epp.package.jee.product
javaRuntimeVersion  1.8.0_151-8u151-b12-0ubuntu0.16.04.2-b12
osgiWs              gtk
osgiOs              Linux
osgiOsVersion       4.4.0
osgiArch            x86_64
severity            UNKNOWN

STATUS

pluginId            org.eclipse.ui
pluginVersion       3.108.1.v20160929-1045
code                0
severity            4
message             Unhandled event loop exception
fingerprint         cfa6244b5083d6c75c353c5b6680b7b0

Exception:java.lang.NullPointerException: null
	 at HIDDEN.HIDDEN(HIDDEN:-1)
	 at org.eclipse.jface.action.Action.runWithEvent(Action.java:473)
	 at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:565)
	 at org.eclipse.jface.action.ActionContributionItem.lambda$5(ActionContributionItem.java:436)
	 at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
	 at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5227)
	 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
	 at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4561)
	 at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4151)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
	 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
	 at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
	 at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:693)
	 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
	 at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:610)
	 at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
	 at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
	 at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	 at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-2)
	 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	 at java.lang.reflect.Method.invoke(Method.java:498)
	 at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	 at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	 at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
	 at org.eclipse.equinox.launcher.Main.main(Main.java:1492)

BUNDLES

name                net.sourceforge.plantuml.eclipse.imagecontrol
version             1.1.19

name                net.sourceforge.plantuml.eclipse
version             1.1.19

name                org.eclipse.core.databinding.observable
version             1.6.0.v20160511-1747

name                org.eclipse.core.databinding
version             1.6.0.v20160412-0910

name                org.eclipse.core.runtime
version             3.12.0.v20160606-1342

name                org.eclipse.e4.ui.workbench
version             1.4.0.v20160517-1624

name                org.eclipse.e4.ui.workbench.swt
version             0.14.1.v20160829-0832

name                org.eclipse.equinox.app
version             1.3.400.v20150715-1528

name                org.eclipse.equinox.launcher
version             1.3.201.v20161025-1711

name                org.eclipse.jface
version             3.12.2.v20170113-2113

name                org.eclipse.swt
version             3.105.3.v20170228-0512

name                org.eclipse.ui
version             3.108.1.v20160929-1045

name                org.eclipse.ui.ide.application
version             1.1.101.v20160829-0827

name                org.eclipse.ui.ide
version             3.12.3.v20170119-0935

**Comment by hallvard** [comment]
There's no reference to plantuml in the stack trace, so I have no clue what the problem can be or how/if it's related to plantuml at all.
