### ISSUE TITLE
An exception occurred while notifying part listeners when opening fxml file and with plantuml view open.

### ISSUE THREAD

**Issue by borgeh** [hallvard/plantuml#77]
java.lang.NoClassDefFoundError: org/eclipse/jdt/internal/ui/javaeditor/IClassFileEditorInput
	at net.sourceforge.plantuml.jdt.ClassFileEditorDiagramTextProvider.getDiagramText(ClassFileEditorDiagramTextProvider.java:22)
	at net.sourceforge.plantuml.text.AbstractDiagramTextProvider.getDiagramText(AbstractDiagramTextProvider.java:41)
	at net.sourceforge.plantuml.text.AbstractDiagramTextProvider.getDiagramText(AbstractDiagramTextProvider.java:36)

**Comment by hallvard** [comment]
Should be fixed now, removed support for generating diagram for class files that caused the problem.
