### ISSUE TITLE
add Ditaa support (@startditaa @endditaa)

### ISSUE THREAD

**Issue by anb0s** [hallvard/plantuml#85]
see: http://plantuml.com/de/ditaa
PlantUML supports Ditaa diagrams too. It would be good if PlantUML view also generates digrams if selected file has sections:
@startditaa
...
@endditaa

**Comment by hallvard** [comment]
I think the issue here is that the ditaa implementation has a license that is incompatible with EPL, which the plugin uses.

**Comment by arnaudroques** [comment]
Yes, it's just a license issue. ditaa is using GPL which is incompatible with EPL (used by Eclipse).
If someone can contact ditaa author (see http://ditaa.sourceforge.net/ ) and ask him if he is ok with EPL, we would be glad to integrate ditaa into future EPL releases.

**Comment by anb0s** [comment]
Thanks, i will ask the author of ditaa.

P.S.: The license issue is about integrating ditaa tool or library with plantuml.jar? Then may be a environment property with path to ditaa*.jar can solve the issue --> user has to install it additionally...

**Comment by anb0s** [comment]
ok i've verified the workaround for the plugin: if i use the @startuml then it does not generated, because not included in the EPL distribution of plantuml.jar:
```
@startuml
ditaa(--no-shadows, scale=0.8)
+--------+   +-------+    +-------+
|        +---+ ditaa +--> |       |
|  Text  |   +-------+    |diagram|
|Document|   |!magic!|    |       |
|     {d}|   |       |    |       |
+---+----+   +-------+    +-------+
  :                         ^
  |       Lots of work      |
  +-------------------------+
@enduml
```
![image](https://user-images.githubusercontent.com/95811/53230291-a39cf180-3686-11e9-9a28-974cb6da2489.png)

**Comment by anb0s** [comment]
> Thanks, i will ask the author of ditaa.

Until now no answer...
 
> P.S.: The license issue is about integrating ditaa tool or library with plantuml.jar? Then may be a environment property with path to ditaa*.jar can solve the issue --> user has to install it additionally...

What do you think ?

**Comment by arnaudroques** [comment]
> What do you think ?
Ok, let's make a first try. There is a special version of PlantUML here http://beta.plantuml.net/noditaa/plantuml.jar which does not contains ditaa classes (you can unzip the jar file to check). However, in the manifest, there is a mention about ditaa0_9.jar
So if you put this special plantuml.jar file and ditaa0_9.jar in the same folder, ditaa diagrams should be processed. Without ditaa0_9.jar it won't work.
Tell us if it's working for you.

**Comment by anb0s** [comment]
I've tried this version first without the ditaa0_9.jar and see expected error:
```
d:\Progs\plantuml_ditaa>java -jar plantuml.jar
java.lang.ClassNotFoundException: org.stathissideris.ascii2image.core.ProcessingOptions
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at net.sourceforge.plantuml.ditaa.PSystemDitaa.<init>(PSystemDitaa.java:67)
        at net.sourceforge.plantuml.ditaa.PSystemDitaaFactory.executeLine(PSystemDitaaFactory.java:87)
        at net.sourceforge.plantuml.ditaa.PSystemDitaaFactory.executeLine(PSystemDitaaFactory.java:1)
        at net.sourceforge.plantuml.command.PSystemBasicFactory.createSystem(PSystemBasicFactory.java:90)
        at net.sourceforge.plantuml.PSystemBuilder.createPSystem(PSystemBuilder.java:121)
        at net.sourceforge.plantuml.BlockUml.getDiagram(BlockUml.java:142)
        at net.sourceforge.plantuml.SourceFileReaderAbstract.getGeneratedImages(SourceFileReaderAbstract.java:147)
        at net.sourceforge.plantuml.DirWatcher2$1.call(DirWatcher2.java:94)
        at net.sourceforge.plantuml.DirWatcher2$1.call(DirWatcher2.java:1)
```

Then i've copied the ditaa0_9.jar to same folder as plantuml.jar and restarted the UI. Now i see no error and it shows that Ditaa diagramms are processed, but it produces only empty (0 bytes) png files (first and last file in this list):
![image](https://user-images.githubusercontent.com/95811/55062826-05ca8700-5077-11e9-8e7f-c4e0748f5a32.png)

**Comment by anb0s** [comment]
Ah ok, it shows error for ditaa files:

```
d:\Progs\plantuml_ditaa>java -jar plantuml.jar
java.lang.NoSuchMethodException: org.stathissideris.ascii2image.core.ConversionOptions.setDropShadows(boolean)
        at java.base/java.lang.Class.getMethod(Unknown Source)
        at net.sourceforge.plantuml.ditaa.PSystemDitaa.exportDiagramNow(PSystemDitaa.java:110)
        at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:135)
        at net.sourceforge.plantuml.PSystemUtils.exportDiagramsDefault(PSystemUtils.java:157)
        at net.sourceforge.plantuml.PSystemUtils.exportDiagrams(PSystemUtils.java:100)
        at net.sourceforge.plantuml.SourceFileReaderAbstract.getGeneratedImages(SourceFileReaderAbstract.java:157)
        at net.sourceforge.plantuml.DirWatcher2$1.call(DirWatcher2.java:94)
        at net.sourceforge.plantuml.DirWatcher2$1.call(DirWatcher2.java:1)
        at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by anb0s** [comment]
Additional info: the plantuml.jar downloaded from official homepage does work with this example...

**Comment by hallvard** [comment]
This isn't necessarily easy in an OSGi environment. It's possible to make a ditaa plugin that is an optional dependency of the plantuml plugin, but this may already be a violation of the license, since such a ditaa plugin will be a redistribution of the underlying ditaa library. I'm not sure it's that easy to allow the end-user to locate the original ditaa jar file and put it somewhere to be discovered and used by the plantuml plugin. I know of an Eclipse plugin that does this, during use it asks whether it should download some jar and if you answer yes it does and then uses it for some task.
